# Generated by Django 4.2.7 on 2026-04-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='organization_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userauth',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrateur'), ('MUNICIPAL_AGENT', 'Agent Mairie'), ('CLUB_MANAGER', 'Gérant de Club Privé'), ('ADVERTISER', 'Annonceur / Marque'), ('USER', 'Sportif (Standard)')], db_index=True, default='USER', max_length=20),
        ),
    ]
