# Generated by Django 4.2.7 on 2026-04-22 01:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userauth_organization_id_userauth_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userauth',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
