# Generated by Django 4.2.7 on 2026-04-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userauth_date_joined_userauth_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userauth',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userauth',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userauth',
            name='push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userauth',
            name='sports_interests',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
