# Generated by Django 4.2.7 on 2025-09-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_numero', models.TextField(blank=True, null=True)),
                ('coordonnees', models.JSONField()),
                ('inst_nom', models.TextField(blank=True, null=True)),
                ('equip_type_name', models.TextField(blank=True, null=True)),
                ('equip_type_famille', models.TextField(blank=True, null=True)),
                ('equip_aps_nom', models.TextField(blank=True, null=True)),
                ('equip_acc_libre', models.BooleanField(default=False)),
                ('equip_url', models.TextField(blank=True, null=True)),
                ('inst_adresse', models.TextField(blank=True, null=True)),
                ('inst_cp', models.TextField(blank=True, null=True)),
                ('equip_prop_nom', models.TextField(blank=True, null=True)),
                ('equip_gest_type', models.TextField(blank=True, null=True)),
                ('inst_acc_handi_bool', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Installation Sportive',
                'verbose_name_plural': 'Installations Sportives',
                'db_table': 'installations',
            },
        ),
    ]
