# Generated by Django 4.2.7 on 2026-04-22 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userauth_date_joined_userauth_last_login'),
        ('installations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='installations.installation')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='authentication.userauth')),
            ],
            options={
                'verbose_name': 'Fréquentation',
                'verbose_name_plural': 'Fréquentations',
                'db_table': 'installations_checkin',
            },
        ),
    ]
